config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/" => "home#index"

  resources :todos

  resources :users

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 3 }
  validates :due_date, presence: true
  belongs_to :user

  def is_due_today?
    due_date == Date.today
  end

  def self.due_today
    where("due_date = ?", Date.today)
  end

  def self.due_later
    where("due_date > ?", Date.today).order(:due_date)
  end

  def self.overdue
    where("due_date < ? and not completed", Date.today).order(:due_date)
  end

  def self.completed
    all.where(completed: true)
  end

  def self.show_list
    puts "My Todo-list\n\n"
    puts "Overdue \n"
    overdue?.map { |todo_item| puts todo_item.to_displayable_string }

    puts "\n\n"
    puts "Due Today\n"
    due_today?.map { |todo_item| puts todo_item.to_displayable_string }

    puts "\n\n"
    puts "Due Later\n"
    due_later?.map { |todo_item| puts todo_item.to_displayable_string }
  end

  def self.mark_as_complete(completed_item_id)
    Todo.update(completed_item_id, completed: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :first_name, length: { minimum: 2 }
  has_secure_password
  has_many :todos

  def to_pleasant_string
    "Welcome #{first_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      #halting the request cycle
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your login attempt was invalid. please retry."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = current_user.todos.find(id)
    render plain: todo.to_pleasant_string
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )

    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )

    if new_user.save
      session[:current_user_id] = new_user.id
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/users/new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class= "Home-title"> Welcome to Todo Homepage </h1>

<h3 class="Home-authenticate">
  if you are a new user, <%= link_to :"sign up here", new_user_path %>
</h3>

<h3 class="Home-authenticate">
  if you are an existing user, <%= link_to :"sign-in here", new_sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name %>!
        <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error"> <%= flash[:error] %> </p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-text"> <%= section_title %> <p>
    <p class="TodoSectionTitle-remainingcount"><%= todos.completed.count %>/<%= todos.count %><p>
  </div>
  <ul>
    <% todos.each do |todo| %>
      <li class="TodoItem">
        <label class="TodoItem-container">
          <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
            <%= check_box_tag("completed", true, todo.completed, { onclick: "this.form.submit();" }) %>
          <% end %>
          <span class='<%= todo.completed ? "TodoItem-completedText" : "" %>'>
            <%= todo.todo_text %>
          </span>
          <% if show_due_date %>
            <p class="TodoItem-dueDate"><%= todo.due_date.to_s(:short) %></p>
          <% end %>
          <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
            <%= image_submit_tag("trash-can-outline.png", class: "TodoItem-delete") %>
          <% end %>
        </label>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<main class="TodoPageMain">
  <article>
    <h1 class="TodoPage-title">My Todo list</h1>
    <%= form_with(url: "/todos", method: "post", class: "AddTodo") do %>
      <%= text_field_tag "todo_text", nil, placeholder: "Whats Next?",
                                           class: "AddTodo-text", autofocus: true %>
      <%= date_field_tag "due_date", nil, class: "AddTodo-date" %>
      <%= submit_tag "Add", class: "AddTodo-button" %>
    <% end %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Overdue",
                 todos: @todos.overdue,
                 show_due_date: true,
               } %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Due Today",
                 todos: @todos.due_today,
                 show_due_date: false,
               } %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Due Later",
                 todos: @todos.due_later,
                 show_due_date: true,
               } %>
  </article>
</main>

app/views/users/new.html.erb
<p class=NewUsers-title > Hi! Welcome New User</p>

<section class="UsersNew">
<%= form_with url: users_path do |form| %>
<div class="Form-section">
  <p class ="FormInput-label"> First Name: </p>
  <%= form.text_field :first_name, class: "Form-input" %>
</div>
<div class="Form-section">
  <p class ="FormInput-label"> Last Name: </p>
  <%= form.text_field :last_name, class: "Form-input" %>
</div>
<div class="Form-section">
  <p class ="FormInput-label"> Email: </p>
  <%= form.email_field :email, class: "Form-input" %>
</div>
<div class="Form-section">
  <p class ="FormInput-label"> Password: </p>
  <%= form.password_field :password, class: "Form-input" %>
</div>
<div class= "Form-section">
  <%= form.submit "Sign-Up!", class: "Form-submit" %>
</div>
<% end %>
</section>